# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: PowerShell@2
  inputs:
    filePath: '.\nugetprocesses.ps1'
